import "../styles/index.css";
import "../styles/login.css";
import "../styles/home.css";
import ClientLayout from "@/components/ClientLayout";

export const metadata = {
  title: "Adel App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Nanum+Myeongjo&display=swap" rel="stylesheet" />
      </head>
      <body>
        <div className="pageContainer">
          <ClientLayout>{children}</ClientLayout>
        </div>
      </body>
    </html>
  );
}
